name: cobiz
description: An intelligent stock management plateform.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  flutter_localizations:
    sdk: flutter

  sqflite: any 
  drift: ^1.6.0
  google_fonts: ^4.0.3
  sqlite3_flutter_libs: ^0.5.0
  fluent_ui: 3.12.0
  window_manager: ^0.2.3
  system_theme: ^2.0.0
  path_provider: any
  path: ^1.0.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  intl: any
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  table_calendar: ^3.0.6
  flutter_acrylic: ^1.0.0+2
  provider: ^6.0.3
  dart_jsonwebtoken: ^2.6.2
  crypt: ^4.2.1
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  velocity_x: 3.5.1
  animate_do: ^2.1.0
  iconsax: ^0.0.8
  shimmer_animation: ^2.1.0+1
  country_code_picker: 2.0.2
  country_pickers: ^2.0.0
  mask_text_input_formatter: 2.3.0
  flutter_svg: ^1.1.6
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.5
  uuid: ^3.0.7
  cloudinary: ^1.1.0
  cached_network_image: ^3.2.3
  animations: ^2.0.7

  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  #drift
  drift_dev: ^1.5.0
  build_runner: ^2.3.3
  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true


  assets: 
    - assets/icons/
    - assets/images/



